# config.yml

backend:
  name: github
  repo: julioct/julioct.github.io
  branch: main # Branch to update (optional; defaults to master)
  site_domain: juliocasal.com

media_folder: 'assets/images'

publish_mode: editorial_workflow

site_url: https://juliocasal.com
logo_url: https://juliocasal.com/images/favicon-light.png

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{title}}
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Featured Image', name: 'featured-image', widget: "image", allow_multiple: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }