# config.yml

backend:
  name: github
  repo: julioct/julioct.github.io
  branch: main # Branch to update (optional; defaults to master)
  site_domain: juliocasal.com

media_folder: 'assets/images'

publish_mode: editorial_workflow

site_url: https://juliocasal.com
logo_url: https://juliocasal.com/images/favicon-light.png

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{title}}
    editor:
      preview: true
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'post'

      - label: 'Featured Image'
        name: 'featured-image'
        widget: 'image'
        allow_multiple: false

      - label: 'Issue Number'
        name: 'issue-number'
        widget: 'number'

      - label: 'Title'
        name: 'title'
        widget: 'string'

      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        default: ''

      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        default: |
          *Read time: X minutes*

          [WHAT THIS POST IS ABOUT]

          [WHY IT IS IMPORTANT]

          [THE CHALLENGE]

          [HOW I'LL SOLVE IT FOR YOU TODAY]

          [CALL TO ACTION]

          <br/>

          ### **TITLE 1**
          BODY

          <br/>

          ### **TITLE 2**
          BODY

          <br/>

          ### **TITLE 3**
          BODY

          <br/>

          ### **TITLE 4**
          BODY

          <br/>

          ### **TITLE 5**
          BODY

          ---

          <br/>

          **Whenever you're ready, there are 2 ways I can help you:**

          1. **[In-depth Courses For .NET Developers](https://juliocasal.com/courses)**: Whether you want to upgrade your software development skills to find a better job, you need best practices for your next project, or you just want to keep up with the latest tech, my in-depth courses will help you get there, step by step. **[Join 800+ students here](https://juliocasal.com/courses)**.
          <br/>

          2. **[Patreon Community](https://www.patreon.com/juliocasal)**. Get access to the source code I use in all my YouTube videos, plus get exclusive discounts for my in-depth courses. **[Join 30+ .NET developers here](https://www.patreon.com/juliocasal)**. }