# config.yml

backend:
  name: github
  repo: julioct/julioct.github.io
  branch: main # Branch to update (optional; defaults to master)
  site_domain: juliocasal.com
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }